// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EA.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace EA.Core.Domain.Models
{
    public partial class Privileges : Entity, IAggregateRoot
    {
        public Privileges()
        {
            Role = new HashSet<Roles>();
            User = new HashSet<Users>();
        }
         
        public Guid ResourceId { get; set; }
        public Guid PermissionId { get; set; }

        public virtual Permissions Permission { get; set; }
        public virtual Resources Resource { get; set; }

        public virtual ICollection<Roles> Role { get; set; }
        public virtual ICollection<Users> User { get; set; }
    }
}