// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EA.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace EA.Core.Domain.Models
{
    public partial class ResAttributes : Entity, IAggregateRoot
    {
        public ResAttributes()
        {
        }

        public string Key { get; set; }
        public string Value { get; set; }
        public Guid ResourceId { get; set; }

        public virtual Resources Resource { get; set; }
    }
}