// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EA.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace EA.Core.Domain.Models
{
    public partial class Resources : Entity, IAggregateRoot
    {
        public Resources()
        {
            Privileges = new HashSet<Privileges>();
            ResAttributes = new HashSet<ResAttributes>();
        }
         
        public string Code { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public int? Parent { get; set; }
        public int? SortOrder { get; set; }

        public virtual ICollection<Privileges> Privileges { get; set; }
        public virtual ICollection<ResAttributes> ResAttributes { get; set; }
    }
}