// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EA.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace EA.Core.Domain.Models
{
    public partial class Roles : Entity, IAggregateRoot
    {
        public Roles()
        {
            Privilege = new HashSet<Privileges>();
            User = new HashSet<Users>();
        }
        public Roles(Guid id, string fullName, string role)
        {
            Id = id;
            FullName = fullName;
            Role = role;
        }
        public Guid Id { get; set; }
        public string FullName { get; set; }
        public string Role { get; set; }
        public string? Description { get; set; }
        public int? Status { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string? ModifiedBy { get; set; }

        public virtual ICollection<Privileges> Privilege { get; set; }
        public virtual ICollection<Users> User { get; set; }
    }
}