// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EA.NetDevPack.Domain;
using EA.NetDevPack.Messaging;
using System;
using System.Collections.Generic;
using EA.Core.Application.Commands.Validations;

namespace EA.Core.Application.Commands
{
    public  class RoleEditCommand : RoleCommand
    {
        public RoleEditCommand(Guid id, string fullName, string role, string? description, 
            int? status, DateTime? createdDate, string? createdBy, DateTime? modifiedDate, string modifiedBy)
        {
            Id = id;
            FullName = fullName;
            Role = role;
            Description = description;
            Status = status;
            CreatedDate = createdDate;
            CreatedBy = createdBy;
            ModifiedBy = modifiedBy;
            ModifiedDate = modifiedDate;
        }

        public override bool IsValid()
        {
            ValidationResult = new RoleEditCommandValidation().Validate(this);
            return ValidationResult.IsValid;
        }
    }
}