// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EA.NetDevPack.Domain;
using EA.NetDevPack.Messaging;
using System;
using System.Collections.Generic;
using EA.Core.Application.Commands.Validations;

namespace EA.Core.Application.Commands
{
    public  class RoleDeleteCommand : RoleCommand
    {
        public RoleDeleteCommand(Guid id, string fullName, string role)
        {
            Id = id;
            FullName = fullName;
            Role = role;
        }

        public override bool IsValid()
        {
            ValidationResult = new RoleDeleteCommandValidation().Validate(this);
            return ValidationResult.IsValid;
        }
    }
}