// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EA.NetDevPack.Domain;
using EA.NetDevPack.Messaging;
using System;
using System.Collections.Generic;
using EA.Core.Application.Commands.Validations;

namespace EA.Core.Application.Commands
{
    public  class RoleAddCommand : RoleCommand
    {

        public RoleAddCommand(Guid id, string fullName, string? role, string? description, int? status)
        {
            Id = id;
            FullName = fullName;
            Role = role;
            Description = description;
            Status = status;
            CreatedBy = CreatedBy;
            ModifiedBy = ModifiedBy;
        }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public override bool IsValid()
        {
            ValidationResult = new RoleAddCommandValidation().Validate(this);
            return ValidationResult.IsValid;
        }
    }
}