// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EA.NetDevPack.Domain;
using EA.NetDevPack.Messaging;
using System;
using System.Collections.Generic;
using EA.Core.Application.Commands.Validations;

namespace EA.Core.Application.Commands
{
    public  class UserDeleteCommand : UserCommand
    {
        public UserDeleteCommand(Guid id, string loginId, string fullName)
        {
            Id = id;
            LoginID = loginId;
            FullName = fullName;
        }

        public override bool IsValid()
        {
            ValidationResult = new UserDeleteCommandValidation().Validate(this);
            return ValidationResult.IsValid;
        }
    }
}