// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EA.NetDevPack.Domain;
using EA.NetDevPack.Messaging;
using System;
using System.Collections.Generic;
using EA.Core.Application.Commands.Validations;

namespace EA.Core.Application.Commands
{
    public  class UserEditCommand : UserCommand
    {
        public UserEditCommand(Guid id, string sub, string loginId, string? loginName, 
            string fullName, string? email, string? address, string? phone, string? photo,
            int? status, DateTime? createdDate, string? createdBy, DateTime? modifiedDate, string modifiedBy)
        {
            Id = id;
            Sub = sub;
            LoginID = loginId;
            LoginName = loginName;
            FullName = fullName;
            Email = email;
            Address = address;
            Phone = phone;
            Photo = photo;
            Status = status;
            CreatedDate = createdDate;
            CreatedBy = createdBy;
            ModifiedBy = modifiedBy;
            ModifiedDate = modifiedDate;
        }

        public override bool IsValid()
        {
            ValidationResult = new UserEditCommandValidation().Validate(this);
            return ValidationResult.IsValid;
        }
    }
}